import {Service,Dentist,BlogPost} from '@/types';
export const services:Service[]=[
{slug:'general-dentistry',name:'General Dentistry',short:'Preventive care that keeps your smile healthy year-round.',description:'From routine exams and cleanings to fillings and gum care, our general dentistry program is built around prevention, comfort and long-term oral health.',duration:'45–60 min',price:'From ₦25,000',icon:'✦',image:'https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1200&q=80',benefits:['Digital oral screening','Gentle professional cleaning','Personalized prevention plan']},
{slug:'cosmetic-dentistry',name:'Cosmetic Dentistry',short:'Natural-looking enhancements designed around your features.',description:'Whitening, bonding and veneers with a conservative philosophy: preserve healthy tooth structure and make every improvement look like you.',duration:'60–90 min',price:'From ₦45,000',icon:'◌',image:'https://images.unsplash.com/photo-1609840114035-3c981b782dfe?auto=format&fit=crop&w=1200&q=80',benefits:['Smile design consultation','Shade-matched results','Digital preview']},
{slug:'invisible-orthodontics',name:'Invisible Orthodontics',short:'Clear aligner treatment with fewer appointments and more confidence.',description:'A discreet way to guide your teeth into healthier alignment using a digitally planned series of clear, removable aligners.',duration:'30–45 min',price:'From ₦850,000',icon:'⌁',image:'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?auto=format&fit=crop&w=1200&q=80',benefits:['3D treatment planning','Progress monitoring','Removable clear trays']},
{slug:'implants',name:'Dental Implants',short:'A durable, natural-feeling replacement for missing teeth.',description:'Implant treatment that restores function and confidence with careful planning, modern imaging and a calm patient-first experience.',duration:'Consultation 45 min',price:'From ₦650,000',icon:'+',image:'https://images.unsplash.com/photo-1588776814546-daab30f310ce?auto=format&fit=crop&w=1200&q=80',benefits:['3D imaging & planning','Surgical guidance','Restorative coordination']},
];
export const dentists:Dentist[]=[
{name:'Dr. Amara Okafor',role:'Lead Dentist · DDS',bio:'Known for gentle chairside care and a prevention-first approach to comprehensive dentistry.',focus:'General & cosmetic',image:'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=800&q=80'},
{name:'Dr. Daniel Mensah',role:'Implantologist · BDS, MSc',bio:'Combines restorative precision with a calm, educational approach to complex treatments.',focus:'Implants & restorative',image:'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=800&q=80'},
{name:'Dr. Zainab Bello',role:'Orthodontist · BDS, MOrth',bio:'Specializes in discreet orthodontics and digital treatment planning for adults and teens.',focus:'Aligners & orthodontics',image:'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=800&q=80'},
];
export const posts:BlogPost[]=[
{slug:'how-often-should-you-visit-the-dentist',title:'How often should you visit the dentist?',excerpt:'A practical guide to checkups, cleanings and the small signs that deserve attention sooner.',category:'Oral health',date:'Sep 6, 2026',read:'5 min read',image:'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1000&q=80'},
{slug:'what-to-expect-from-a-first-visit',title:'What to expect from your first visit',excerpt:'From arrival to your treatment plan, here is how we make the first appointment feel simple.',category:'Patient guide',date:'Aug 21, 2026',read:'4 min read',image:'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1000&q=80'},
{slug:'five-habits-for-a-healthier-smile',title:'Five habits for a healthier smile',excerpt:'Small daily habits can protect your teeth and gums more than you might expect.',category:'Wellness',date:'Aug 3, 2026',read:'6 min read',image:'https://images.unsplash.com/photo-1559591937-e2c4e7d8d9ff?auto=format&fit=crop&w=1000&q=80'},
];
